#
# CrateX, a Crate plugin for PocketMine-MP
# Copyright (c) 2018 EmeraldAssasin  < https://github.com/N/A >
#
# Discord: N/A
# Twitter: N/A
#
# This software is distributed under "GNU General Public License v3.0".
# This license allows you to use it and/or modify it but you are not at
# all allowed to sell this plugin at any cost. If found doing so the
# necessary action required would be taken.
#
# MysteryCrate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License v3.0 for more details.
#
# You should have received a copy of the GNU General Public License v3.0
# along with this program. If not, see
# <https://opensource.org/licenses/GPL-3.0>.
#  -----------------------------------------------------------------------

# The ID:META of the key you want to use for opening crates.
# Its better not to edit this value unless you can edit the source code.
key: "131:0"

# The the description for the Key.
descOne: "§dCrateKey For §bCubeX"
descTwo: "§cTier §4Level§6 > §b1"

# Enter the name of the FOLDER of the world in which crate is located.
# Example if your world name is spawn but folder name is spw then enter spw in crateWorld
WorldCrate: "Lobby"

# Set the value you want the command to be recognized with. Make sure its in between 10-50
# If you want to reward the player with a command, set the meta of the reward in the crates.yml
# to the value you set in commandMeta.
commandMeta: 50

# Set for how long you want the task to run. Increasing this value will increase the
# time taken for the player to earn the reward and vice versa.
# Recommended to set it to 2.
# Enter the value in seconds.
tickDelay: 2
